# Generated by Django 4.2.7 on 2023-11-29 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(choices=[('SINGLE', 'unico'), ('PACK', 'pack')], default='SINGLE', max_length=32)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.product')),
            ],
            options={
                'verbose_name': 'ProductTag',
                'verbose_name_plural': 'ProductTags',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'porcentaje'), ('FIXED', 'plano')], default='PERCENTAGE', max_length=32)),
                ('value', models.FloatField(default=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='product.product')),
            ],
            options={
                'verbose_name': 'ProductDiscount',
                'verbose_name_plural': 'ProductDiscounts',
                'ordering': ('start_date',),
            },
        ),
    ]
