# Generated by Django 4.2.7 on 2023-12-09 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'BlogCategory',
                'verbose_name_plural': 'BlogCategories',
                'ordering': ('category',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField(blank=True, max_length=1024)),
                ('active', models.BooleanField(default=True)),
                ('publish_data', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('title',),
            },
        ),
    ]
