# Generated by Django 4.2.7 on 2023-12-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('category',), 'verbose_name': 'BlogCategory', 'verbose_name_plural': 'BlogCategories'},
        ),
    ]
