# Generated by Django 4.2.7 on 2023-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
