# Generated by Django 4.2.7 on 2023-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
